config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  resource :sessions, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new'
  resources :orders, :customers
  resources :order_products
  resources :prices

  namespace :admin do
    root to: '/admin#index'
    resources :users, :colors, :materials, :sizes, :products
    resources :workers
    resources :product_groups, :product_materials
    resources :products do
      member do
        get 'clone'
      end
    end
  end

  namespace :operator do
    get 'storage', to: 'storage#index'
    resources :inputs, :outputs, :providers
    resources :input_materials, :output_materials
  end
end

app/models/output.rb
class Output < ActiveRecord::Base
  validates :num, :date, :order, presence: true
  validates :num, uniqueness: true

  has_many :materials, through: :output_materials
  has_many :output_materials, dependent: :destroy

  belongs_to :worker
end

app/controllers/operator/input_materials_controller.rb
class Operator::InputMaterialsController < ApplicationController
  before_action :set_material, only: [:edit, :update, :destroy, :object]

  def new
    @input_material = InputMaterial.new(input_id: params[:input])
  end

  def create
    @input_material = InputMaterial.new(material_params)
    render :new && return unless @input_material.save
    # @input_material.material.update(count: @input_material.material.count +
                                    # @input_material.count)
  end

  def edit
    # @input = @input_material.product
  end

  def update
    render :edit unless @input_material.update(material_params)
  end

  def destroy
    # TODO: show error notification
    # @input_material.material.update(count: @input_material.material.count -
                                    # @input_material.count)
    @input_material.destroy
  end

  private

  def set_material
    @input_material = InputMaterial.find(params[:id])
  end

  def material_params
    params.require(:input_material).permit!
  end

  def object
    @input_material
  end
  helper_method :object
end

app/controllers/operator/inputs_controller.rb
class Operator::InputsController < ApplicationController
  before_action :set_input, only: [:show, :edit, :update, :destroy, :object]

  def index
    @inputs = Input.all
    @input = Input.new
  end

  def new
    @input = Input.new
    @providers = Provider.all
  end

  def create
    @input = Input.new(input_params)
    render :new unless @input.save
  end

  def show
    @input_material = InputMaterial.new(input_id: @input.id)
    @materials = InputMaterial.materials(@input.id)
  end

  def edit
  end

  def update
    render :edit unless @input.update(input_params)
  end

  def destroy
    # TODO: show error notification
    @input.destroy
  end

  private

  def set_input
    @input = Input.find(params[:id])
  end

  def input_params
    params.require(:input).permit!
  end

  def object
    @input
  end
  helper_method :object
end

app/controllers/operator/output_materials_controller.rb
class Operator::OutputMaterialsController < ApplicationController
  before_action :set_material, only: [:edit, :update, :destroy, :object]

  def new
    @output_material = OutputMaterial.new(output_id: params[:output])
  end

  def create
    @output_material = OutputMaterial.new(material_params)
    render(:new) && return unless @output_material.save
    @output_material.material.update(count: @output_material.material.count -
                                    @output_material.count)
  end

  def edit
  end

  def update
    render :edit unless @output_material.update(material_params)
  end

  def destroy
    # TODO: show notification if error
    @output_material.material.update(count: @output_material.material.count +
                                    @output_material.count)
    @output_material.destroy
  end

  private

  def set_material
    @output_material = OutputMaterial.find(params[:id])
  end

  def material_params
    params.require(:output_material).permit!
  end

  def object
    @output_material
  end
  helper_method :object
end

app/controllers/operator/outputs_controller.rb
class Operator::OutputsController < ApplicationController
  before_action :set_output, only: [:show, :edit, :update, :destroy, :object]

  def index
    @outputs = Output.all
    @output = Output.new
  end

  def new
    @output = Output.new
  end

  def show
    @output_material = OutputMaterial.new(output: @output)
    @materials = OutputMaterial.materials(@output.id)
  end

  def edit
  end

  def create
    @output = Output.new(output_params)
    render :new unless @output.save
  end

  def update
    render :edit unless @output.update(output_params)
  end

  def destroy
    @output.destroy
    # TODO: show notification if can't delete item
  end

  private

  def set_output
    @output = Output.find(params[:id])
  end

  def output_params
    params.require(:output).permit!
  end

  def object
    @output
  end
  helper_method :object
end

app/controllers/operator/providers_controller.rb
class Operator::ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy, :object]

  def index
    @providers = Provider.all.order(:name)
    @provider = Provider.new
  end

  def new
    @provider = Provider.new
  end

  def show
  end

  def edit
  end

  def create
    @provider = Provider.new(provider_params)
    render :new unless @provider.save
  end

  def update
    render :edit unless @provider.update(provider_params)
  end

  def destroy
    # TODO: show error notification
    @provider.destroy
  end

  private

  def set_provider
    @provider = Provider.find(params[:id])
  end

  def provider_params
    params.require(:provider).permit!
  end

  def object
    @provider
  end
  helper_method :object
end

app/controllers/operator/storage_controller.rb
class Operator::StorageController < ApplicationController
  def index
    @materials = Material.all.order(:name)
  end
end

app/views/operator/outputs/_form.html.slim
.new_output
  = simple_form_for [:operator, @output], remote: true  do |f|
    .row
      .col.m6
        => f.input :num, label: t('output.num')
      .col.m6
        => f.input :date, as: :string, label: t('output.date'), input_html: { class: 'datepicker' }
    .row
      .col.m6
        => f.input :order, label: t('output.order')
      .col.m6
        => f.association :worker, label: t('output.worker')
    => f.submit t('form.create'), class: 'btn waves-effect waves-light'

app/views/operator/outputs/_output.html.slim
tr id="output_#{output.id}"
  td= output.num
  td= output.date
  td= output.order
  td= output.worker.name if output.worker
  td
    => link_to t('output.show'), operator_output_path(output), class: 'btn waves-effect waves-light'
    => delete_item_link operator_output_path(output)

app/views/operator/outputs/_output_details.html.slim
p
  span.bold= "#{t('output.num')}: "
  span= @output.num
p
  span.bold= "#{t('output.date')}: "
  span= @output.date
p
  span.bold= "#{t('output.order')}: "
  span= @output.order

app/views/operator/outputs/_output_show.html.slim
p
  span.bold= "#{t('output.num')}: "
  span= @output.num
p
  span.bold= "#{t('output.date')}: "
  span= @output.date
p
  span.bold= "#{t('output.order')}: "
  span= @output.order

app/views/operator/outputs/index.html.slim
= render partial: 'application/collapsible_form', locals: { title: t('output.create'), form: 'form' }

table.bordered.striped
  thead
    tr
      th= t('output.num')
      th= t('output.date')
      th= t('output.order')
      th= t('output.worker')
      th
  tbody#outputs
    = render @outputs

app/views/operator/outputs/new.html.slim
h1= t('outputs.new')

= render 'form'

app/views/operator/outputs/show.html.slim
= render 'output_details'

table.bordered.striped
  thead
    tr
      th= t('output_material.name')
      th= t('output_material.count')
      th
  tbody#output_materials
    = render partial: 'operator/output_materials/output_material', collection: @materials

ul.collapsible
  li
    .collapsible-header
      i.material-icons create
      = t('output_material.create')
    .collapsible-body.form-padding
      = render partial: 'operator/output_materials/form'