config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  resource :sessions, only: [:new, :create, :destroy]

  get 'login', to: 'sessions#new'
  resources :orders, :customers
  resources :order_products
  resources :prices

  namespace :admin do
    root to: '/admin#index'
    resources :users, :colors, :materials, :sizes, :products
    resources :workers
    resources :product_groups, :product_materials
    resources :products do
      member do
        get 'clone'
      end
    end
  end

  namespace :operator do
    get 'storage', to: 'storage#index'
    resources :inputs, :outputs, :providers
    resources :input_materials, :output_materials
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :product_group, presence: true
  validates :image, allow_blank: true, format: { with: /\.(jpg|png)/ }

  belongs_to :product_group
  belongs_to :size
  belongs_to :color

  has_many :product_materials, dependent: :destroy
  has_many :materials, through: :product_materials

  mount_uploader :image, ImageUploader

  def name_with_group
    [product_group.name, name].join(' - ')
  end

  def full_name
    full_name = product_group.name << ' ' << name
    full_name << ', ' << size.name if size
    full_name
  end

  scope :for_group, -> (group) { where('product_group_id = ?', group) }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize

  def index
    @product = Product.new
    @products = Product.all.order(:product_group_id)
    @product_groups = ProductGroup.all
  end

  def show
    @materials = ProductMaterial.materials(@product.id)
  end

  def new
    @product = Product.new(product_group_id: params[:product_group])
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    # @product = Product.new(name: params[:product][:name],
                           # size_id: params[:product][:size_id],
                           # product_group: params[:product_group])
    render :new unless @product.save
  end

  def update
    render :edit unless @product.update(product_params)
  end

  def destroy
    # TODO: show error notification
    @product.destroy
  end

  def clone
    old = Product.find(params[:id])
    product = Product.create(old.attributes.reject do |k, _v|
      k == ('id' || 'image')
    end)
    ProductMaterial.where('product_id = ?', params[:id]).each do |material|
      @product_material = material.dup
      @product_material.product = product
      @product_material.save
    end
    redirect_to admin_product_path(product.id)
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit!
  end
end

app/views/admin/products/_form.html.slim
.new_product
  /* h4= @product.product_group.name */
  = simple_form_for [:admin, @product], remote: true do |f|
    => f.hidden_field :product_group_id, value: params[:product_group]
    => f.input :name, label: t('product.name')
    => f.association :size, collection: Size.for_group(params[:product_group]), include_blank: true, label_method: :name, label: t('size.title')
    => f.input :image, as: :file, label_html: { class: 'active' }, label: t('product.image')
    br
    => f.submit t('form.save'), class: 'btn waves-effect waves-light'

app/views/admin/products/_product.html.slim
tr.walign-wrapper id="product_#{product.id}"
  td.m2= image_tag(product.image_url(:thumb)) if product.image_url
  td.m4= product.name
  td.m3= product.size.name if product.size
  td.m4.right-align
    => link_to t('product.cart'), admin_product_path(product), class: 'btn waves-effect waves-light'
    => delete_item_link(admin_product_path(product))

app/views/admin/products/_product_show.html.slim
.product
  .row.pd
    .col-md-4
      h4= t('product.cart')
      p= @product.product_group.name
      p= @product.name
      p= @product.size.name unless @product.size.nil?
      p= @product.description
    .col-md-2
      = link_to t('form.edit'), edit_admin_product_path(@product.id), remote: true, class: 'btn btn-info'
      = link_to t('product_material.create'), new_admin_product_material_path(product_id: @product.id), remote: true, class: 'btn btn-success'
    .col-md-6.text-right
      = image_tag @product.image_url(:big)

app/views/admin/products/index.html.slim
ul.collapsible id='product_groups_buttons'
  li
    .collapsible-header
      i.material-icons create
      = t('product.create')
    .collapsible-body.form-padding.row
      .col.m3.collection
        - @product_groups.each do |g|
          = link_to g.name, new_admin_product_path(product_group: g.id), remote: true, id: "form_pg_#{g.id}", class: 'collection-item'
      .col.m9#product_form

- @product_groups.each do |group|
  ul.collapsible id="product_group_#{group.id}" data-collapsible='expandable'
    li
      .collapsible-header
        = group.name
      .collapsible-body
        table
          tbody
            - @products.each do |product|
              - if product.product_group_id == group.id
                = render partial: 'product', object: product

app/views/admin/products/show.html.slim
= render 'product_show'

.row
  .panel.panel-primary
    .panel-heading
      h3 class='panel-title'
        = t('product.material.title')
    .panel-body
      .panel.panel-info#joinery
        .panel-heading
          h3 class='panel-title'
            = t('product.joinery')
        .panel-body
          = render partial: 'admin/product_materials/product_material', collection: @materials.joinery

      .panel.panel-info#grinding
        .panel-heading
          h3 class='panel-title'
            = t('product.grinding')
        .panel-body
          = render partial: 'admin/product_materials/product_material', collection: @materials.grinding

      .panel.panel-info#painting
        .panel-heading
          h3 class='panel-title'
            = t('product.painting')
        .panel-body
          = render partial: 'admin/product_materials/product_material', collection: @materials.painting

      .panel.panel-info#assembly
        .panel-heading
          h3 class='panel-title'
            = t('product.assembly')
        .panel-body
          = render partial: 'admin/product_materials/product_material', collection: @materials.assembly

= link_to t('clone'), clone_admin_product_path(params[:id]), class: 'btn btn-success'